#pragma once

#define LAPIC_SVR_APIC (1<<8)

#define LAPIC_REG_ID  0x020
#define LAPIC_REG_TPR 0x080
#define LAPIC_REG_EOI 0x0B0
#define LAPIC_REG_SVR 0x0F0
#define LAPIC_REG_LVT 0x320
#define LAPIC_REG_INITCNT 0x380
#define LAPIC_REG_CURRCNT 0x390
#define LAPIC_REG_DIVCFG 0x3E0

#define LAPIC_TIMER_MODE_ONE_SHOT 0x0
#define LAPIC_TIMER_MODE_PERIODIC 0x1
#define LAPIC_TIMER_MODE_TSC_DLINE 0x2

#define LAPIC_TIMER_DIVIDE_2 0x0
#define LAPIC_TIMER_DIVIDE_4 0x1
#define LAPIC_TIMER_DIVIDE_8 0x2
#define LAPIC_TIMER_DIVIDE_16 0x3
#define LAPIC_TIMER_DIVIDE_32 0x4
#define LAPIC_TIMER_DIVIDE_64 0x5
#define LAPIC_TIMER_DIVIDE_128 0x6
#define LAPIC_TIMER_DIVIDE_1 0x7
